import Head from 'next/head'

interface CustomHeadProps {
    route_title?: string
}

const CustomHead = ({ route_title }: CustomHeadProps) => {
    return (
        <Head>
            <meta charSet="utf-8" />
            <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
            <meta
                name="viewport"
                content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"
            />
            <meta name="keywords" content="Keywords" />

            <link rel="manifest" href="/manifest.json" />
            <link rel="apple-touch-icon" href="/icon.png"></link>
            <meta name="theme-color" content="#317EFB" />

            <title>MyLib{route_title ? `: ${route_title}` : ''}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
        </Head>

    )
}

export default CustomHead